project_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
# from tasks.views import index

urlpatterns = [
    path('', include('tasks.urls')),
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('quality_control/', include('quality_control.urls')),
]

quality_control/urls.py
from django.urls import path
from quality_control import views

app_name = 'quality_control'

urlpatterns = [
    # path('', views.index, name='start_quality'),
    path('', views.IndexView.as_view(), name='index'),
    path('bugs/', views.bug_list, name='bugs_page'),
    path('features/', views.feature_list, name='feat_page'),

    path('bugs/new/', views.add_bug_report, name="new_bug"),                                                    #C
    path('features/new/', views.add_feat_request, name="new_feat"),                                             #C
    path('bugs/new/', views.BugReportCreateView.as_view(), name="new_bug"),                                     #C
    path('features/new/', views.FeatureRequestCreateView.as_view(), name="new_feat"),                           #C

    path('bugs/<int:bug_id>/', views.bug_detail, name='bug_detail'),                                            #R
    path('features/<int:feature_id>/', views.feature_detail, name='feature_detail'),                            #R
    path('bugs/<int:bug_id>/', views.BugReportDetailView.as_view(), name='bug_detail'),                         #R
    path('features/<int:feature_id>/', views.FeatureRequestDetailView.as_view(), name='feature_detail'),        #R

    path('bugs/<int:bug_id>/update', views.update_bug, name='update_bug'),                                      #U
    path('features/<int:feature_id>/update', views.update_feature, name='update_feature'),                      #U
    path('bugs/<int:bug_id>/update', views.BugReportUpdateView.as_view(), name='update_bug'),                   #U
    path('features/<int:feature_id>/update', views.FeatureRequestUpdateView.as_view(), name='update_feature'),  #U

    path('bugs/<int:bug_id>/delete', views.delete_bug, name='delete_bug'),                                      #D
    path('features/<int:feature_id>/delete', views.delete_feature, name='delete_feature'),                      #D
    path('bugs/<int:bug_id>/delete', views.BugReportDeleteView.as_view(), name='delete_bug'),                   #D
    path('features/<int:feature_id>/delete', views.FeatureRequestDeleteView.as_view(), name='delete_feature'),  #D
]

tasks/urls.py
from django.urls import path
from tasks import views

app_name = 'tasks'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('projects/', views.projects_list, name='projects_list'),
    # path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    # path('projects/<int:project_id>/tasks/<int:task_id>/', views.task_detail, name='task_detail'),

    path('', views.IndexView.as_view(), name='index'),
    path('projects/', views.ProjectsListView.as_view(), name='projects_list'),
    path('projects/<int:project_id>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:project_id>/tasks/<int:task_id>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('feedback/', views.feedback_view, name='feedback'),

    path('project/new/', views.create_project, name='create_project'),
    path('project/<int:project_id>/add_task/', views.add_task_to_project, name='add_task_to_project'),
    path('project/create/', views.ProjectCreateView.as_view(), name='create_project'),
    path('project/<int:project_id>/add_task/', views.TaskCreateView.as_view(), name='add_task_to_project'),

    path('project/<int:project_id>/update/', views.update_project, name='update_project'),
    path('project/<int:project_id>/task/<int:task_id>/update/', views.update_task, name='update_task'),
    path('project/<int:project_id>/update/', views.ProjectUpdateView.as_view(), name='update_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/update/', views.TaskUpdateView.as_view(), name='update_task'),

    # path('project/<int:project_id>/delete/', views.delete_project, name='delete_project'),
    # path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('project/<int:project_id>/delete/', views.ProjectDeleteView.as_view(), name='delete_project'),
    path('project/<int:project_id>/tasks/<int:task_id>/delete/', views.TaskDeleteView.as_view(), name='delete_task'),

    ]

quality_control/models.py
from django.db import models

from tasks.models import Project, Task
class BugReport(models.Model):
    STATUS_CHOISES = [
        ('New', 'Новая'),
        ('In_progress', 'В работе'),
        ('Completed', 'Завершена')
    ]

    PRIORITY_CHOISES = [
        ('Low', 'Низкий'),
        ('Middle', 'Средний'),
        ('Height', 'Высокий'),
        ('Very_height', 'Очень высокий'),
        ('Critical', 'Критический')
    ]

    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

    description = models.TextField()
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='bugs',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOISES,
        default='New'
    )
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOISES,
        default='Middle'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class FeatureRequest(models.Model):
    STATUS_CHOISES = [
        ('Consideration', 'Рассмотрение'),
        ('Accepted', 'Принято'),
        ('Rejected', 'Отклонено')
    ]

    PRIORITY_CHOISES = [
        ('Low', 'Низкий'),
        ('Middle', 'Средний'),
        ('Height', 'Высокий'),
        ('Very_height', 'Очень высокий'),
        ('Critical', 'Критический')
    ]

    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

    description = models.TextField()
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE
    )
    task = models.ForeignKey(
        Task,
        related_name='requests',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOISES,
        default='Consideration'
    )
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOISES,
        default='Middle'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

quality_control/forms.py
from django import forms
from django.forms import ModelForm
from .models import BugReport, FeatureRequest

class BugReportForm(ModelForm):
    class Meta:
        model = BugReport
        fields =['title','description','project','task','status', 'priority']
class FeatureRequestForm(ModelForm):
    class Meta:
        model = FeatureRequest
        fields = ['title','description','project','task','status', 'priority']

quality_control/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse
from .models import BugReport, FeatureRequest

# def index(request):
#     return render(request, 'quality_control/index.html')

def bug_list(request):
    bugs = BugReport.objects.all()
    return render(request, 'quality_control/bug_list.html', {'bugs': bugs})


def feature_list(request):
    features = FeatureRequest.objects.all()
    return render(request, 'quality_control/feature_list.html', {'features': features})


from django.views import View
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'quality_control/index.html')

############################################################################################
#############READ#####################READ#######READ################READ###READ##############
############################################################################################
def bug_detail(request, bug_id):
    bug = get_object_or_404(BugReport, id=bug_id)
    return render(request, 'quality_control/bug_detail.html', {'bug': bug})
def feature_detail(request, feature_id):
    feat = get_object_or_404(FeatureRequest, id=feature_id)
    return render(request, 'quality_control/feature_detail.html', {'feat': feat})

from django.views.generic import DetailView
class BugReportDetailView(DetailView):
    model = BugReport
    pk_url_kwarg = "bug_id"
    template_name = 'quality_control/bug_detail.html'
    context_object_name = 'bug'

class FeatureRequestDetailView(DetailView):
    model = FeatureRequest
    pk_url_kwarg = "feature_id"
    template_name = 'quality_control/feature_detail.html'
    context_object_name = 'feat'


############################################################################################
#############CREATE#####################CREATE#######CREATE#################################
############################################################################################
from .forms import BugReportForm, FeatureRequestForm
def add_bug_report(request):
    if request.method == 'POST':
        form = BugReportForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bugs_page')
    else:
        form = BugReportForm()
    return render(request, 'quality_control/bug_create.html', {'form': form})

def add_feat_request(request):
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feat_page')
    else:
        form = FeatureRequestForm()
    return render(request, 'quality_control/feature_create.html', {'form': form})

from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

class BugReportCreateView(CreateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_create.html'
    success_url = reverse_lazy('quality_control:bugs_page')
    context_object_name = 'bug'

class FeatureRequestCreateView(CreateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_create.html'
    success_url = reverse_lazy('quality_control:feat_page')
    context_object_name = 'feature'

############################################################################################
#######UPDATE#############UPDATE###########UPDATE#############UPDATE########UPDATE##########
############################################################################################

def update_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    if request.method == 'POST':
        form = BugReportForm(request.POST, instance=bug)
        if form.is_valid():
            form.save()
            return redirect('quality_control:bug_detail', bug_id=bug_id)
    else:
        form = BugReportForm(instance=bug)
    return render(request, 'quality_control/bug_update.html', {'form': form, 'bug': bug})


def update_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    if request.method == 'POST':
        form = FeatureRequestForm(request.POST, instance=feature)
        if form.is_valid():
            form.save()
            return redirect('quality_control:feature_detail', feature_id=feature_id)
    else:
        form = FeatureRequestForm(instance=feature)
    return render(request, 'quality_control/feature_update.html', {'form': form, 'feature': feature})

class BugReportUpdateView(UpdateView):
    model = BugReport
    form_class = BugReportForm
    template_name = 'quality_control/bug_update.html'
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bug_list')
    context_object_name = 'bug'


class FeatureRequestUpdateView(UpdateView):
    model = FeatureRequest
    form_class = FeatureRequestForm
    template_name = 'quality_control/feature_update.html'
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feature_list')
    context_object_name = 'feat'

############################################################################################
#######DELETE#############DELETE###########DELETE#############DELETE########DELETE##########
############################################################################################

def delete_bug(request, bug_id):
    bug = get_object_or_404(BugReport, pk=bug_id)
    bug.delete()
    return redirect('quality_control:bugs_page')

def delete_feature(request, feature_id):
    feature = get_object_or_404(FeatureRequest, pk=feature_id)
    feature.delete()
    return redirect('quality_control:feat_page')

class BugReportDeleteView(DeleteView):
    model = BugReport
    pk_url_kwarg = 'bug_id'
    success_url = reverse_lazy('quality_control:bugs_page')
    context_object_name = 'bug'
    template_name = 'quality_control/bug_confirm_delete.html'


class FeatureRequestDeleteView(DeleteView):
    model = FeatureRequest
    pk_url_kwarg = 'feature_id'
    success_url = reverse_lazy('quality_control:feat_page')
    context_object_name = 'feature'
    template_name = 'quality_control/feature_confirm_delete.html'

quality_control/templates/quality_control/bug_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление отчёта об ошибке</h1>
    <p>Вы уверены, что хотите удалить отчёт об ошибке "{{ bug.title }}"?</p>

    <form action="{% url 'quality_control:delete_bug' bug.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:bugs_page' %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_create.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить баг репорт</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить баг репорт</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/bug_detail.html
{% extends 'base/base.html' %}

{% block title %}
    {{ bug.title }}
{% endblock %}

{% block content %}
    <h1>Детали бага {{ bug.id }}</h1>
    <p><a href="{% url 'quality_control:update_bug' bug.id %}">Изменить отчёт об ошибке</a></p>
    <ul>
        <li>Название: {{ bug.title }}</li>
        <li>Описание: {{ bug.description }}</li>
        <li>Статус: {{ bug.status }}</li>
        <li>Приоритет: {{ bug.priority }}</li>
        <li>Проект: {{ bug.project }}</li>
        <li>Задача: {{ bug.task }}</li>
    </ul>
<p><a href="{% url 'quality_control:delete_bug' bug.id %}" onclick="return confirm('Вы уверены, что хотите удалить этот отчёт об ошибке?');">Удалить отчёт об ошибке</a></p>
{% endblock %}

quality_control/templates/quality_control/bug_list.html
{% extends 'base/base.html' %}

{% block title %}
    Список багов
{% endblock %}

{% block content %}
    <h1>Список багов</h1>


    <p><a href="{% url 'quality_control:new_bug' %}">Сообщить о новом баге</a></p>


    <ul>
        {% for bug in bugs %}
            <li><a href="{% url 'quality_control:bug_detail' bug.id %}">{{bug.title}}</a> - Статус: {{bug.status}}</li>
        {% empty %}
            <li>Список багов пуст.</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/bug_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение отчёта об ошибке: {{ bug.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feat_page' %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_create.html
{% extends 'base/base.html' %}

{% block content %}
    <h2>Добавить запрос на улучшение</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить запрос</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/feature_detail.html
{% extends 'base/base.html' %}

{% block title %}
    {{ feat.tittle }}
{% endblock %}

{% block content %}
    <h1>Детали запроса на улучшение {{ feat.id }}</h1>
    <p><a href="{% url 'quality_control:update_feature' feat.id %}">Изменить запрос на улучшение</a></p>
    <ul>
        <li>Название: {{ feat.title }}</li>
        <li>Описание: {{ feat.description }}</li>
        <li>Статус: {{ feat.status }}</li>
        <li>Приоритет: {{ feat.priority }}</li>
        <li>Проект: {{ feat.project }}</li>
        <li>Задача: {{ feat.task }}</li>
    </ul>
    <p><a href="{% url 'quality_control:delete_feature' feat.id %}" onclick="return confirm('Вы уверены, что хотите удалить этот запрос на улучшение?');">Удалить запрос на улучшение</a></p>
{% endblock %}

quality_control/templates/quality_control/feature_list.html
{% extends 'base/base.html' %}

{% block title %}
    Список запросов на улучшение
{% endblock %}

{% block content %}
    <h1>Список запросов на улучшение</h1>

    <p><a href="{% url 'quality_control:new_feat' %}">Создать запрос на улучшение</a></p>


    <ul>
        {% for feat in features %}
            <li><a href="{% url 'quality_control:feature_detail' feat.id %}">{{feat.title}}</a> - Статус: {{feat.status}}</li>
        {% empty %}
            <li>Список запросов на улучшение пуст.</li>
        {% endfor %}
    </ul>
{% endblock %}

quality_control/templates/quality_control/feature_update.html
{% extends 'base/base.html' %}

{% block content %}
<h2>Изменение запроса на улучшение: {{ feat.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить</button>
    </form>
{% endblock %}

quality_control/templates/quality_control/featurerequest_confirm_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Удаление запроса на улучшение</h1>
    <p>Вы уверены, что хотите удалить запрос на улучшение "{{ feature.title }}"?</p>

    <form action="{% url 'quality_control:delete_feature' feature.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
        <a href="{% url 'quality_control:feat_page' %}">Отмена</a>
    </form>
{% endblock %}

quality_control/templates/quality_control/index.html
{% extends 'base/base.html' %}

{% block title %}
 Контроль качества
{% endblock %}

{% block content %}
        <h1>Система контоля качества</h1>
        <ul>
            <li><a href="{% url 'quality_control:bugs_page' %}">Список всех багов</a></li>
            <li><a href="{% url 'quality_control:feat_page' %}">Запросы на улучшение</a></li>
        </ul>
{% endblock %}